# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_csv_file = "cities.csv"

weather_df = pd.read_csv(weather_csv_file)

weather_df.head()

,City,Cloudiness,Country,Date,Humidity,Latitude,Longitude,Max Temp,Wind Speed
0,qaqortoq,25,GL,1635050896,62,60.7167,-46.0333,34.30,5.66
1,shache,14,CN,1635050897,20,38.4167,77.2406,56.14,4.18
2,kudahuvadhoo,94,MV,1635050337,73,2.6708,72.8944,82.94,12.80
3,turayf,0,SA,1635050660,50,31.6725,38.6637,52.05,6.91
4,sisimiut,100,GL,1635050299,84,66.9395,-53.6735,21.20,7.25

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Configure gmaps with API key.
gmaps.configure(api_key=g_key)

# Convert Humidity to float and store
# Also, handle NaN values
weather_df = weather_df.dropna()
humidity = weather_df["Humidity"].astype(float)

# Store 'Latitude' and 'Longitude' into locations. 
locations = weather_df[["Latitude", "Longitude"]].astype(float)

# Create a humidity Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=max(weather_df["Humidity"]),
                                 point_radius = 2)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [4]:
# Narrow down the DataFrame to find your ideal weather condition.
filtered_weather_df = weather_df

# Drop any rows that don't contain all three conditions. Want to be sure the weather is ideal.

# A max temperature lower than 80 degrees but higher than 70.
filtered_weather_df = filtered_weather_df.loc[(filtered_weather_df["Max Temp"] < 80) & (filtered_weather_df["Max Temp"] > 70)]

# Wind speed less than 10 mph.
filtered_weather_df = filtered_weather_df.loc[filtered_weather_df["Wind Speed"] < 10]

# Zero cloudiness.
filtered_weather_df = filtered_weather_df.loc[filtered_weather_df["Cloudiness"] == 0]

# Drop any rows with null values
filtered_weather_df = filtered_weather_df.dropna()

filtered_weather_df

,City,Cloudiness,Country,Date,Humidity,Latitude,Longitude,Max Temp,Wind Speed
16,beloha,0,MG,1635050902,54,-25.1667,45.0500,77.76,3.04
51,jiwani,0,PK,1635050915,70,25.0500,61.7417,79.63,4.63
86,darab,0,IR,1635050928,21,28.7519,54.5444,71.78,3.76
169,salalah,0,OM,1635050962,65,17.0151,54.0924,78.89,3.44
200,sohagpur,0,IN,1635050973,51,22.7000,78.2000,79.25,1.32
268,sarh,0,TD,1635050999,88,9.1429,18.3923,75.11,0.00
304,mutare,0,ZW,1635051016,35,-18.9707,32.6709,79.66,2.04
386,morondava,0,MG,1635051046,51,-20.2833,44.2833,77.95,7.25

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [5]:
hotel_df = filtered_weather_df

# params dictionary to update each iteration
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key
}


for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Latitude"]
    lng = row["Longitude"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {row['City']}.")
    response = requests.get(base_url, params=params).json()
    # print(json.dumps(response, indent=4, sort_keys=True))
    
    # extract results
    results = response['results']
    
    try:
        print(f"Closest hotel is {results[0]['name']}.")
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

Retrieving Results for Index 16: beloha.
Missing field/result... skipping.
------------
Retrieving Results for Index 51: jiwani.
Closest hotel is Al Mumtaz Transport Jiwani.
------------
Retrieving Results for Index 86: darab.
Closest hotel is Naghshe shapoor Hotel.
------------
Retrieving Results for Index 169: salalah.
Closest hotel is HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel.
------------
Retrieving Results for Index 200: sohagpur.
Closest hotel is Hotel Vatika Inn- A unit of Hotel Ramayan.
------------
Retrieving Results for Index 268: sarh.
Closest hotel is Domicile 1sur le goudron.
------------
Retrieving Results for Index 304: mutare.
Closest hotel is Ann Bruce Backpackers.
------------
Retrieving Results for Index 386: morondava.
Closest hotel is La Case Bambou.
------------

In [6]:
hotel_df

,City,Cloudiness,Country,Date,Humidity,Latitude,Longitude,Max Temp,Wind Speed,Hotel Name
16,beloha,0,MG,1635050902,54,-25.1667,45.0500,77.76,3.04,NaN
51,jiwani,0,PK,1635050915,70,25.0500,61.7417,79.63,4.63,Al Mumtaz Transport Jiwani
86,darab,0,IR,1635050928,21,28.7519,54.5444,71.78,3.76,Naghshe shapoor Hotel
169,salalah,0,OM,1635050962,65,17.0151,54.0924,78.89,3.44,"HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel"
200,sohagpur,0,IN,1635050973,51,22.7000,78.2000,79.25,1.32,Hotel Vatika Inn- A unit of Hotel Ramayan
268,sarh,0,TD,1635050999,88,9.1429,18.3923,75.11,0.00,Domicile 1sur le goudron
304,mutare,0,ZW,1635051016,35,-18.9707,32.6709,79.66,2.04,Ann Bruce Backpackers
386,morondava,0,MG,1635051046,51,-20.2833,44.2833,77.95,7.25,La Case Bambou

In [7]:
# Assign the marker layer to a variable
locations = hotel_df[["Latitude", "Longitude"]]
markers = gmaps.marker_layer(locations)

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [8]:
# Create hotel symbol layer
hotel_layer = gmaps.symbol_layer(
    locations, fill_color='rgba(0, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=2,
    info_box_content=hotel_info
)
# Add the layer to the map
fig.add_layer(markers)
fig.add_layer(hotel_layer)
fig

Figure(layout=FigureLayout(height='420px'))